version: '3'

services:
  gowiki:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GOWIKI_SLACK_TOKEN
      - GOWIKI_DB_CONFIG  
    links:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:9.6-alpine
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    
    
    